- hosts: all
  become: ec2-user
  tasks: 
    - name: create new deployment
      command: kubectl apply -f /home/ec2-user/Deployment.yml 
    - name: create new service
      command: kubectl apply -f /home/ec2-user/Service.yml
