- hosts: ansible_server
  become: ec2-user
  tasks: 
    - name: create docker image
      command: docker build -t $JOB_NAME:v1.$BUILD_ID . 
    - name: create tag to image
      command: docker tag $JOB_NAME:v1.$BUILD_ID  sibhisky/$JOB_NAME:v1.$BUILD_ID
    - name: create tag to image
      command: docker tag $JOB_NAME:v1.$BUILD_ID  sibhisky/$JOB_NAME:latest 
    - name: push image to dockerhub
      command: docker push sibhisky/$JOB_NAME:v1.$BUILD_ID
    - name: push image to dockerhub
      command: docker push sibhisky/$JOB_NAME:latest
      
