apiVersion: apps/v1
kind: Deployment
metadata:
  name: sibhi-deployment
spec: 
  replicas: 2
  selector:
    matchlabels:
      app: cb    
  template:
    metadata:
      labels:
        app: myapp
  Spec:
    containers:
    - name: sibhi
      image: sibhisky/sibhi_project
      ports:
      - containerPort: 80
