apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec: 
  replicas: 2
  selector:
    matchlabels:
      app: tomcat    
  template:
    metadata:
      labels:
        app: myapp
  Spec:
    containers:
    - name: tomcatlatest
      image: tomcat
      ports:
      - containerPort: 80
