apiVersion: v1
kind: Service
metadata: 
  name: loadbalancer
spec:
  type: LoadBalancer
  Selector:
    app: myapp
  ports:
    - port: 8090
      targetport: 80
      nodePort: 32000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cb    
  template:
    metadata:
      labels:
        app: myapp
  Spec:
    containers:
    - name: sibhi
      image: sibhisky/sibhi_project:latest
      ports:
      - containerPort: 80
